---
kind: pipeline
type: docker
name: build-x86_64-linux

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: docker.io/nixos/nix
    commands:
      - "nix-env -iA nixpkgs.nixFlakes"
      - "echo 'experimental-features = nix-command flakes ca-references' >> /etc/nix/nix.conf"
      - "echo 'max-jobs = auto' >> /etc/nix/nix.conf"
      - "nix profile install github:NixOS/nixpkgs/nixos-unstable-small#git"
      - "nix build github:NixOS/nix#nix.inputDerivation"
      - "nix --substituters '' --repeat 20 build github:NixOS/nix#nix -vL"
